version: "3.9"

services:
  prod:
    container_name: kmc-reimbursement-app
    image: kmc-reimbursement-app:latest
    platform: "linux/amd64"
    build:
      context: .
      args:
        NODE_ENV: "production"
        NEXT_PUBLIC_ENVIRONMENT: "production"
        NEXT_PUBLIC_PUSHER_APP_KEY: "affa5695ab0f6d72e6b5"
        NEXT_PUBLIC_AUTH_URL: "https://171091628.propelauthtest.com"

    ports:
      - 3000:3000
