version: "3.9"

services:
  prod:
    container_name: kmc-reimbursement-app
    image: kmc-reimbursement-app:latest
    platform: "linux/amd64"
    build:
      context: .
      args:
        NODE_ENV: "production"
        NEXT_PUBLIC_ENVIRONMENT: "production"
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
        NEXT_PUBLIC_AUTH_URL: ${NEXT_PUBLIC_AUTH_URL}
        PROPELAUTH_API_KEY: ${PROPELAUTH_API_KEY}
        PROPELAUTH_VERIFIER_KEY: ${PROPELAUTH_VERIFIER_KEY}
        PROPELAUTH_REDIRECT_URI: ${PROPELAUTH_REDIRECT_URI}
        NEXT_PUBLIC_PUSHER_APP_KEY: ${PUSHER_APP_KEY}

    ports:
      - 3000:3000
