name: Docker Image CI

on:
  push:
    branches: ["main", "development"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  CURRENT_BRANCH: ""

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    environment: ${{ (github.ref == 'refs/heads/main' && 'Production') || 'Development' }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set current branch name
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "Setting branch name to 'main'"
            echo "CURRENT_BRANCH=main" >> $GITHUB_ENV
          else
            echo "Setting branch name to 'development'"
            echo "CURRENT_BRANCH=development" >> $GITHUB_ENV
          fi

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}_${{ env.CURRENT_BRANCH }}
          tags: |
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            NODE_ENV=production
            NEXT_PUBLIC_ENVIRONMENT=${{ secrets.NEXT_PUBLIC_ENVIRONMENT }}
            PROPELAUTH_API_KEY=${{ secrets.PROPELAUTH_API_KEY }}
            PROPELAUTH_VERIFIER_KEY=${{ secrets.PROPELAUTH_VERIFIER_KEY }}
            PROPELAUTH_REDIRECT_URI=${{ secrets.PROPELAUTH_REDIRECT_URI }}
            NEXT_PUBLIC_APP_URL=${{ secrets.NEXT_PUBLIC_APP_URL }}
            NEXT_PUBLIC_AUTH_URL=${{ secrets.NEXT_PUBLIC_AUTH_URL }}
            NEXT_PUBLIC_PUSHER_APP_KEY=${{ secrets.NEXT_PUBLIC_PUSHER_APP_KEY }}

  delete-old-packages-keep-3-latest:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Delete old packages but keep 3 latest
        uses: smartsquaregmbh/delete-old-packages@v0.7.0
        with:
          organization: kmcwebdev
          # supported types: npm, maven, rubygems, docker, nuget, container
          type: container
          keep: 3
          names: |
            reimbursement_client_app_main
            reimbursement_client_app_development
