name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "development"]
jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      SKIP_ENV_VALIDATION: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run lint
        run: pnpm lint
