import { z } from "zod";

export const appClaimsSchema = z.enum([
  "CAN_APPROVE_REIMBURSEMENT",
  "CAN_GENERATE_REIMBURSEMENT_REPORT",
  "CAN_BULK_APPROVE_REIMBURSEMENT",
  "CAN_BULK_REJECT_REIMBURSEMENT",

  //Layout Permissions
  "NAV_ITEM_APPROVAL",
  "NAV_ITEM_HISTORY",
  "REIMBURSEMENT_VIEW_APPROVAL",
  "REIMBURSEMENT_VIEW_DOWNLOAD_HOLD",
  "USER",
  "USER_PROFILE",
]);
